name    'justinhennessy-sdiff'
version '1.0.0'
source 'git://github.com/justinhennessy/sdiff'
author 'Justin Hennessy and Alexandra Spillane'
summary 'sdiff Module'
description 'A puppet module for suppressing diff output based on file and line regex'
project_page 'git://github.com/justinhennessy/sdiff'
