name    'justinhennessy-sdiff'
version '1.0.1'
source 'git://github.com/justinhennessy/sdiff'
author 'Justin Hennessy and Alexandra Spillane'
summary 'Provides suppressing diff output based on file and line regex'
description 'A puppet module for suppressing diff output based on file and line regex'
project_page 'git://github.com/justinhennessy/sdiff'
